USE master
GO 

ALTER DATABASE  dbName  SET  EMERGENCY
GO

DBCC checkdb ('dbName')
GO

ALTER DATABASE dbName SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

DBCC CHECKDB (dbName, REPAIR_ALLOW_DATA_LOSS)
GO

ALTER DATABASE dbName SET MULTI_USER
GO